DatasetsShareWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sharingPlatform.urls')),
    path('auth/', include('qwjAuth.urls'))
]

qwjAuth/urls.py
from django.urls import path
from . import views

app_name = 'qwjAuth'

urlpatterns = [
    path('login/', views.qwjlogin, name='login'),
    path('register/', views.register, name='register'),
    path('captcha/', views.send_eamil_captcha, name='captcha'),
    path('logout/', views.qwjlogout, name='logout')
]

sharingPlatform/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'sharingPlatform'

urlpatterns = [
                  path('', views.index, name='index'),
                  path("dataset/details/<int:dataset_id>", views.dataset_details, name='dataset_details'),
                  path("dataset/pub", views.pub_dataset, name='pub_dataset'),
                  path("dataset/comment/pub", views.pub_comment, name="pub_comment"),
                  path("search", views.search, name="search"),
                  path("dataset/detail/download/<int:dataset_id>", views.download_dataset_file,
                       name="download_dataset_file"),
                  path("dataset/my_datasets", views.search_myself, name="search_myself"),
                  path("dataset/delete/<int:dataset_id>", views.dataset_delete, name="dataset_delete"),
                  path("dataset/edit/<int:dataset_id>", views.edit_dataset, name="dataset_edit")
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'CSS/base.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
<header class="p-3 text-bg-light border-bottom mb-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'images/share.svg' %}" alt="" height="40">
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'sharingPlatform:index' %}" class="nav-link px-2 text-secondary">首页</a></li>
                {#                <li><a href="{% url 'sharingPlatform:pub_dataset' %}"#}
                {#                       class="nav-link px-2 text-secondary">分类数据集</a></li>#}
                <li><a href="{% url 'sharingPlatform:pub_dataset' %}"
                       class="nav-link px-2 text-secondary">上传数据集</a></li>
                {#                <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>#}
                {#                <li><a href="#" class="nav-link px-2 text-white">About</a></li>#}
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search"
                  action="{% url 'sharingPlatform:search' %}" method="GET">
                <input type="search" class="form-control " placeholder="搜索数据集..."
                       aria-label="Search" name="q">
            </form>
            {% if user.is_authenticated %}
                <div class="dropdown text-end">
                    <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'images/defaultAvatar.svg' %}" alt="mdo" width="32" height="32"
                             class="rounded-circle">
                    </a>
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item" href="{% url 'sharingPlatform:search_myself' %}">我的数据集</a>
                        </li>
                        {#                        <li><a class="dropdown-item" href="#">Settings</a></li>#}
                        {#                        <li><a class="dropdown-item" href="#">Profile</a></li>#}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'qwjAuth:logout' %}">退出登录</a></li>
                    </ul>
                </div>
            {% else %}
                <div class="text-end">
                    <a href={% url 'qwjAuth:login' %} type="button" class="btn btn-outline-primary me-2">登录</a>
                    <a href="{% url 'qwjAuth:register' %}" type="button" class="btn btn-primary">注册</a>
                </div>
            {% endif %}
        </div>
    </div>
</header>
<main class="container bg-white p-3 rounded border-success-subtle">
    {% block main %}{% endblock %}
</main>
</body>
</html>

templates/dataset_detail.html
{% extends 'base.html' %}
{% block head %}
    <link rel="stylesheet" href="{% static 'highlight/styles/github-dark-dimmed.min.css' %}">
    <script src="{% static 'highlight/highlight.min.js' %}"></script>
{% endblock %}
{% block title %}
    数据集详情
{% endblock %}
{% block main %}
    <h1>{{ dataset.name }}</h1>
    <hr>
    <div>
        <img src="{% static 'images/defaultAvatar.svg' %}" class="rounded-circle" height="30" width="30" alt="">
        <span class="ms-1">{{ dataset.author.username }}</span>
        <span class="ms-1">于</span>
        <span class="ms-1">{{ dataset.pub_time|date:"Y年m月d日 H时i分" }}</span>发布
        {% if request.user == dataset.author %}
            <a href="{% url 'sharingPlatform:dataset_edit' dataset_id=dataset.id %}"
               class="btn btn-primary">编辑数据集</a>
            <a href="{% url 'sharingPlatform:dataset_delete' dataset_id=dataset.id %}"
               class="btn btn-danger" onclick="return confirm('你确定要删除这个数据集吗？')">删除</a>
        {% endif %}
    </div>
    <hr>
    <div class="py-2">
        <h2>{{ dataset.content|safe }}</h2>
    </div>
    {% if dataset.file %}
        <div class="mt-2">
            <a href="{% url 'sharingPlatform:download_dataset_file' dataset_id=dataset.id %}" class="btn btn-success">下载数据集</a>
        </div>
    {% endif %}
    <hr>
    <div class="mt-2">
        <h3>评论（{{ dataset.comments.all|length }}）</h3>
        <form action="{% url 'sharingPlatform:pub_comment' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="dataset_id" value="{{ dataset.id }}">
            <div class="mt-2">
                <input type="text" class="form-control" placeholder="请输入评论..." name="content">
            </div>
            <div class="text-end mt-2">
                <button type="submit" class="btn btn-primary">发布评论</button>
            </div>
        </form>
    </div>
    <div class="mt-2">
        <ul class="list-group list-group-flush">
            {% for comment in dataset.comments.all %}
                <li class="list-group-item mb-3">
                    <div class="d-flex justify-content-between text-body-secondary">
                        <div class="user-info">
                            <img src="{% static 'images/defaultAvatar.svg' %}" class="rounded-circle" height="40"
                                 width="40"
                                 alt="">
                            <span class="ms-2">{{ comment.author.username }}</span>
                        </div>
                        <div class="create-time" style="line-height: 40px">
                            {{ comment.pub_time|date:"Y年m月d日 H时i分" }}
                        </div>
                    </div>
                    <div class="mt-2">{{ comment.content }}</div>
                </li>
            {% endfor %}
        </ul>
    </div>
    <script>
        hljs.highlightAll();
    </script>

{% endblock %}

templates/edit_dataset.html
{% extends 'base.html' %}
{% block head %}
    <script src={% static 'js/dataset_edit.js' %}></script>
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'wangeditor/style.css' %}">
    <script src="{% static 'wangeditor/index.js' %}"></script>
    <style>
        #editor—wrapper {
            border: 1px solid #ccc;
            z-index: 100; /* 按需定义 */
        }

        #toolbar-container {
            border-bottom: 1px solid #ccc;
        }

        #editor-container {
            height: 500px;
        }
    </style>
{% endblock %}
{% block title %}
    编辑数据集
{% endblock %}
{% block main %}
    <h1>编辑你的数据集信息</h1>
    <div class="mb-3">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label class="form-label">标题</label>
                <input type="text" name="name" id="DatasetName" class="form-control" value="{{ dataset.name }}">
            </div>
            <div class="mb-3">
                <label class="form-label">分类</label>
                <select name="category" class="form-select" id="category-select">
                    {% for category in categories %}
                        <option value="{{ category.id }}"
                                {% if category.id == dataset.category.id %}selected{% endif %}>{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label class="form-label">描述你的数据集如何使用</label>
                <div id="editor—wrapper">
                    <div id="toolbar-container"><!-- 工具栏 --></div>
                    <div id="editor-container"><!-- 编辑器 --></div>
                </div>
            </div>
            <div class="mb-3">
                <label class="form-label">上传文件</label>
                <input type="file" name="file" class="form-control" id="file-upload">
                <small class="form-text text-muted">当前文件: {{ dataset.file.name }}</small>
            </div>
            <div class="mb-3 text-end">
                <button class="btn btn-primary" id="submit-btn">发布</button>
            </div>
        </form>
    </div>
    <script>
        const {createEditor, createToolbar} = window.wangEditor

        const editorConfig = {
            placeholder: 'Type here...',
            onChange(editor) {
                const html = editor.getHtml()
                console.log('editor content', html)
                // 也可以同步到 <textarea>
            }
        }

        const editor = createEditor({
            selector: '#editor-container',
            html: '{{ dataset.content|safe|escapejs }}',
            config: editorConfig,
            mode: 'default', // or 'simple'
        })

        const toolbarConfig = {}

        const toolbar = createToolbar({
            editor,
            selector: '#toolbar-container',
            config: toolbarConfig,
            mode: 'default', // or 'simple'
        })
        dataset_id = {{ dataset.id }}
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}深度学习共享数据集平台{% endblock %}
{% block main %}
    <h1>数据集列表</h1>
    {% for category, datasets in datasets_grouped_by_category.items %}
        <h2 class="mt-5">{{ category.name }}</h2>
        <hr>
        <div class="row row-cols-2 row-gap-2">
            {% for dataset in datasets %}
                <div class="col">
                    <div class="card">
                        <div class="card-header">
                            <a href="{% url 'sharingPlatform:dataset_details' dataset_id=dataset.id %}">{{ dataset.name }}</a>
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ dataset.content|striptags|truncatechars:200 }}</p>
                            <a href="{% url 'sharingPlatform:dataset_details' dataset_id=dataset.id %}"
                               class="btn btn-primary">点击查看数据集详情</a>
                            {% if user == dataset.author %}
                                <a href="{% url 'sharingPlatform:dataset_delete' dataset_id=dataset.id %}"
                                   class="btn btn-danger" onclick="return confirm('你确定要删除这个数据集吗？')">删除</a>
                            {% endif %}
                        </div>
                        <div class="card-footer text-body-secondary d-flex justify-content-between">
                            <div>
                                <img src="{% static 'images/defaultAvatar.svg' %}" class="rounded-circle" height="30"
                                     width="30"
                                     alt="">
                                {{ dataset.author.username }}
                            </div>
                            <div>
                                发布时间： {{ dataset.pub_time|date:"Y年m月d日 H时i分" }}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block title %}登录{% endblock %}
{% block main %}
    <div style="max-width: 300px;" class="m-auto">
        <h1 class="mb-3">登录</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label class="mb-3">邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="输入邮箱">
            </div>
            <div class="mb-3">
                <label class="mb-3">密码</label>
                <input type="password" name="password" class="form-control" placeholder="输入密码">
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" name="remember_me" value="1" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    记住我
                </label>
            </div>
            <div class="mt-3">
                <button class="btn btn-primary w-100">立即登录</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/my_databases.html
{% extends 'base.html' %}
{% block title %}{{ user.username }}的数据集列表{% endblock %}
{% block main %}
    <h1>{{ user.username }}的数据集列表</h1>
    {% for category, datasets in datasets_grouped_by_category.items %}
        <h2 class="mt-5">{{ category.name }}</h2>
        <hr>
        <div class="row row-cols-2 row-gap-2">
            {% for dataset in datasets %}
                <div class="col">
                    <div class="card">
                        <div class="card-header">
                            <a href="{% url 'sharingPlatform:dataset_details' dataset_id=dataset.id %}">{{ dataset.name }}</a>
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ dataset.content|striptags|truncatechars:200 }}</p>
                            <a href="{% url 'sharingPlatform:dataset_details' dataset_id=dataset.id %}"
                               class="btn btn-primary">点击查看数据集详情</a>
                            {% if user == dataset.author %}
                                <a href="{% url 'sharingPlatform:dataset_delete' dataset_id=dataset.id %}"
                                   class="btn btn-danger" onclick="return confirm('你确定要删除这个数据集吗？')">删除</a>
                            {% endif %}
                        </div>
                        <div class="card-footer text-body-secondary d-flex justify-content-between">
                            <div>
                                <img src="{% static 'images/defaultAvatar.svg' %}" class="rounded-circle" height="30"
                                     width="30"
                                     alt="">
                                {{ dataset.author.username }}
                            </div>
                            <div>
                                发布时间： {{ dataset.pub_time|date:"Y年m月d日 H时i分" }}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}

templates/pub_dataset.html
{% extends 'base.html' %}
{% block head %}
    <script src={% static 'js/dataset_pub.js' %}></script>
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'wangeditor/style.css' %}">
    <script src="{% static 'wangeditor/index.js' %}"></script>
    <style>
        #editor—wrapper {
            border: 1px solid #ccc;
            z-index: 100; /* 按需定义 */
        }

        #toolbar-container {
            border-bottom: 1px solid #ccc;
        }

        #editor-container {
            height: 500px;
        }
    </style>
{% endblock %}
{% block title %}
    发布你的数据集
{% endblock %}
{% block main %}
    <h1>填写你的数据集信息</h1>
    <div class="mb-3">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label class="form-label">标题</label>
                <input type="text" name="name" id="DatasetName" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">分类</label>
                <select name="category" class="form-select" id="category-select">
                    {% for category in categories %}
                        <option value={{ category.id }}>{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label class="form-label">描述你的数据集如何使用</label>
                <div id="editor—wrapper">
                    <div id="toolbar-container"><!-- 工具栏 --></div>
                    <div id="editor-container"><!-- 编辑器 --></div>
                </div>
            </div>
            <div class="mb-3">
                <label class="form-label">上传文件</label>
                <input type="file" name="file" class="form-control" id="file-upload">
            </div>
            <div class="mb-3 text-end">
                <button class="btn btn-primary" id="submit-btn">发布</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block title %}
    注册
{% endblock %}

{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/register.js' %}"></script>
{% endblock %}

{% block main %}
    <div style="max-width: 300px;" class="m-auto">
        <h1 class="mb-3">注册</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label>用户名</label>
                <input type="text" name="username" class="form-control" placeholder="输入用户名">
            </div>
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="输入邮箱">
            </div>
            <div class="mb-3">
                <label>验证码</label>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="captcha" placeholder="输入验证码"
                           aria-label="Recipient's username" aria-describedby="basic-addon2">
                    <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                </div>
            </div>

            <div class="mb-3">
                <label>密码</label>
                <input type="password" name="password" class="form-control" placeholder="输入密码">
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" name="remember" value="1" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    记住我
                </label>
            </div>
            <div class="mt-3">
                <button class="btn btn-primary w-100">立即注册</button>
            </div>
        </form>
    </div>
{% endblock %}